const SHOWS_ACTORS_TABLE = 'SHOW_ACTORS';
const ACTORS_TABLE = 'ACTORS';
const SHOWS_TABLE = 'SHOWS';

export const PATCH_SHOWS_ACTORS = `REPLACE INTO ${SHOWS_ACTORS_TABLE} (show_id, actor_id) VALUES ?`;

export const GET_SHOW_ACTORS = `
    SELECT * FROM
        (SELECT * FROM ${SHOWS_TABLE} s ORDER BY CONVERT(s.SHOW_ID, SIGNED INTEGER) LIMIT ? OFFSET ?) as s

        LEFT JOIN ${SHOWS_ACTORS_TABLE} sa
            ON s.SHOW_ID = sa.SHOW_ID

        LEFT JOIN ${ACTORS_TABLE} a
            ON sa.ACTOR_ID = a.ACTOR_ID
`
