version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - db
    command: npm run serve-debug
  db:
    build:
      context: ./
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password